name: lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Check doc link
        run: |
          python .github/scripts/doc_link_checker.py --target doc
          python .github/scripts/doc_link_checker.py --target README.md
          python .github/scripts/doc_link_checker.py --target README_ENGLISH.md
      - name: Install pre-commit hook
        run: |
          # markdownlint requires ruby >= 2.7
          sudo apt-add-repository ppa:brightbox/ruby-ng -y
          sudo apt-get update
          sudo apt-get install -y ruby2.7
          pip install pre-commit
          pre-commit install
